# Generated by Django 5.1.1 on 2024-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.IntegerField(null=True),
        ),
    ]
