# Generated by Django 5.1.1 on 2024-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_enrollmentstudent_enrollmentteacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='attendance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
