# Generated by Django 5.1.1 on 2024-10-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
