# Generated by Django 5.1.1 on 2024-10-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_attendance_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='assignment',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='assignments/'),
        ),
    ]
