# Generated by Django 5.1.1 on 2024-10-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_attendance_pdf_file_assignment_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
