# Generated by Django 5.1.1 on 2024-10-11 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_assignment_attendance_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='attendance_verified',
            new_name='assignment_verified',
        ),
    ]
