# Generated by Django 5.1.1 on 2024-10-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='late_days',
            field=models.IntegerField(default=0),
        ),
    ]
